version: '3.8'

services:
  guardian-angel:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    container_name: guardian_angel_core
    restart: unless-stopped

    # GPU support
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video

    # Volumes
    volumes:
      - ../../configs:/app/configs
      - ../../data:/app/data
      - ../../logs:/app/logs
      - ../../models:/app/models

    # Network mode (host for better RTSP performance)
    network_mode: host

    # Resource limits (adjust based on hardware)
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
